openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /patient/update/{id}:
    put:
      tags:
      - patient-controller
      operationId: update
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PatientRequestDto"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/PatientResponseDto"
  /medicalrecord/update/{id}:
    put:
      tags:
      - medical-record-controller
      operationId: update_1
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MedicalRecordRequestDto"
      responses:
        "200":
          description: OK
  /doctor/update/{id}:
    put:
      tags:
      - doctor-controller
      operationId: update_2
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DoctorRequestDto"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/DoctorResponseDto"
  /appointment/update/{id}:
    put:
      tags:
      - appointment-controller
      operationId: update_3
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AppointmentRequestDto"
        required: true
      responses:
        "200":
          description: OK
  /patient/create:
    post:
      tags:
      - patient-controller
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PatientRequestDto"
        required: true
      responses:
        "200":
          description: OK
  /medicalrecord/create:
    post:
      tags:
      - medical-record-controller
      operationId: create_1
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MedicalRecordRequestDto"
      responses:
        "200":
          description: OK
  /doctor/create:
    post:
      tags:
      - doctor-controller
      operationId: create_2
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DoctorRequestDto"
        required: true
      responses:
        "200":
          description: OK
  /appointment/create:
    post:
      tags:
      - appointment-controller
      operationId: create_3
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AppointmentRequestDto"
        required: true
      responses:
        "200":
          description: OK
  /patient/readById/{id}:
    get:
      tags:
      - patient-controller
      operationId: readById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/PatientResponseDto"
  /patient/readAll:
    get:
      tags:
      - patient-controller
      operationId: readAll
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PatientResponseDto"
  /medicalrecord/readById/{id}:
    get:
      tags:
      - medical-record-controller
      operationId: readById_1
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/MedicalRecordResponseDto"
  /medicalrecord/readAll:
    get:
      tags:
      - medical-record-controller
      operationId: readAll_1
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/MedicalRecordResponseDto"
  /doctor/readById/{id}:
    get:
      tags:
      - doctor-controller
      operationId: readById_2
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/DoctorResponseDto"
  /doctor/readAll:
    get:
      tags:
      - doctor-controller
      operationId: readAll_2
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DoctorResponseDto"
  /appointment/readById/{id}:
    get:
      tags:
      - appointment-controller
      operationId: readById_3
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/AppointmentResponseDto"
  /appointment/readAll:
    get:
      tags:
      - appointment-controller
      operationId: readAll_3
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/AppointmentResponseDto"
  /patient/delete/{id}:
    delete:
      tags:
      - patient-controller
      operationId: deleteById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
  /medicalrecord/delete/{id}:
    delete:
      tags:
      - medical-record-controller
      operationId: delete
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
  /doctor/delete/{id}:
    delete:
      tags:
      - doctor-controller
      operationId: delete_1
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
  /appointment/delete/{id}:
    delete:
      tags:
      - appointment-controller
      operationId: delete_2
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
components:
  schemas:
    PatientRequestDto:
      type: object
      properties:
        name:
          type: string
        age:
          type: integer
          format: int32
        height:
          type: number
          format: float
        weight:
          type: number
          format: float
    PatientResponseDto:
      type: object
      properties:
        patient_id:
          type: integer
          format: int64
        name:
          type: string
        age:
          type: integer
          format: int32
        height:
          type: number
          format: float
        weight:
          type: number
          format: float
    MedicalRecordRequestDto:
      type: object
      properties:
        medicalCondition:
          type: string
        patient_id:
          type: integer
          format: int64
    DoctorRequestDto:
      type: object
      properties:
        name:
          type: string
        age:
          type: integer
          format: int32
        specialization:
          type: string
        department:
          type: string
    DoctorResponseDto:
      type: object
      properties:
        doctor_id:
          type: integer
          format: int64
        name:
          type: string
        age:
          type: integer
          format: int32
        specialization:
          type: string
        department:
          type: string
    AppointmentRequestDto:
      type: object
      properties:
        appointmentDate:
          type: string
          format: date
        appointmentTime:
          $ref: "#/components/schemas/LocalTime"
        doctor_id:
          type: integer
          format: int64
        patient_id:
          type: integer
          format: int64
    LocalTime:
      type: object
      properties:
        hour:
          type: integer
          format: int32
        minute:
          type: integer
          format: int32
        second:
          type: integer
          format: int32
        nano:
          type: integer
          format: int32
    MedicalRecordResponseDto:
      type: object
      properties:
        medicalrecord_id:
          type: integer
          format: int64
        medicalCondition:
          type: string
        patientDto:
          $ref: "#/components/schemas/PatientResponseDto"
    AppointmentResponseDto:
      type: object
      properties:
        appointment_id:
          type: integer
          format: int64
        appointmentDate:
          type: string
          format: date
        dayOfWeek:
          type: string
          enum:
          - MONDAY
          - TUESDAY
          - WEDNESDAY
          - THURSDAY
          - FRIDAY
          - SATURDAY
          - SUNDAY
        appointmentTime:
          $ref: "#/components/schemas/LocalTime"
        patientDto:
          $ref: "#/components/schemas/PatientResponseDto"
        doctorDto:
          $ref: "#/components/schemas/DoctorResponseDto"
